name: Publish Docker image

on:
  push:
    branches: [ main ] 		# Работает в ветке master или main

permissions:
  contents: write 			# разрешаем пайплайну делать коммиты в репо

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-24.04
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }} 	# логин в докер-хабе
          password: ${{ secrets.DOCKER_TOKEN }} 		# пароль в докер-хабе

      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./server/
          push: true 					# сохраняем свежий образ на докер-хабе
          tags: ${{ secrets.DOCKER_USERNAME }}/devops-psu:latest

# часть пайплайна заносит дату сборки в файл манифеста и коммитит в ветвку release. 
#Это требуется чтобы на CD стадии мы увидели не просто коммит, а обновление манифеста.

  touch-k8s-manifest:
    needs: [ push_to_registry ]
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Insert release date 		# подменяем дату (обновляем манифест)
        run: 'sed -i "s/release-date: .*$/release-date: s`date +%s`/g" ./server-k8s-manifests/devops-psu.yml'

      - name: Commit manifest
        run: |				# сохраняем изменения манифеста в ветке release
          git config --global user.name 'Release Runner'
          git config --global user.email 'runner@users.noreply.github.com'
          git commit -am "Release"
          git push --force origin main:release